apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rumours
  name: rumours
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rumours
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: rumours
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
